name: catamm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - pandas
  - jupyter
  - ipykernel
  - pip
  - pip:
    - pygame
    - networkx
    - plotly
    - seaborn